version: '2'
services:
  db:
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - db
    expose:
      - 8090
    ports:
      - 8090:8090
    environment:
      - DATABASE_NAME=todo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
    restart: unless-stopped